#!/usr/bin/env bash


MAPBOX_TOKEN="pk.eyJ1IjoiY2J5cmRhMTQiLCJhIjoiY2p3OTR1dzV4MjJ1cDN6cXJmOTZuZWhhaiJ9.9zv76ioomyEmyweDP486BA"

### test data
# zoom=16
# lat=14.605715499999999
# lon=121.095042

lat=$1
lon=$2
zoom=$3

style="styles/v1/mapbox/light-v10"

url="https://api.mapbox.com/$style/static/$lon,$lat,$zoom/1280x1280@2x?access_token=$MAPBOX_TOKEN"

curl $url -o $4.png
convert $4.png -type truecolor $4.bmp
rm $4.png
